spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/email_validation
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
        ddl-auto: create-drop
        database: postgresql
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect